### ISSUE TITLE
Why does CreateAsync return Task<IEnumerable<TItem>>?

### ISSUE THREAD

**Issue by danielmarbach** [IEvangelist/azure-cosmos-dotnet-repository#3] opened 2020-10-09 10:46 UTC
https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/IRepository.cs#L78

return `Task<IEnumerable<TItem>>` while

https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/IRepository.cs#L64

returns `ValueTask<IEnumerable<TItem>>` any reasons why they are not alike?

Also, [notice the xml doc is not up to date](https://github.com/IEvangelist/azure-cosmos-dotnet-repository/blob/main/Microsoft.Azure.CosmosRepository/src/IRepository.cs#L77). Happy to send a PR if wanted. It seems though changing the interface return type is a breaking change so I wanted to ask first

**Comment by IEvangelist** [comment] 2020-10-09 12:49
Hi @danielmarbach - thank you for posting the issue first, and asking the question. This is [by design](https://stackoverflow.com/questions/45689327/task-whenall-for-valuetask).

When calls are made to create  multiple items at the same time, they're pushed into a `Task.WhenAll` and each `ValueTask` calls `.AsTask` as there is not an equivalent function for `ValueTask`. I decided to just have that API be represented as `Task` and left the others as the optimal `ValueTask`.

**Comment by IEvangelist** [comment] 2020-10-09 16:28
Hi @danielmarbach - I like it! Thank you for the suggestion. I'll implement this and make it part of 2.0.0.

**Comment by IEvangelist** [comment] 2020-10-09 16:50
Fixed by: https://github.com/IEvangelist/azure-cosmos-dotnet-repository/commit/db0756f43938546f3ceb0c9f8a7738a08550cd08

**Closed by IEvangelist** 2020-10-09 16:50 UTC

**Comment by danielmarbach** [comment] 2020-10-09 21:48
😍🤩Glad my rambling was helpful
