### ISSUE TITLE
Filtering by type seems broken

### ISSUE THREAD

**Issue by jiggyswift** [IEvangelist/azure-cosmos-dotnet-repository#51] opened 2021-06-15 01:17 UTC
The type filtering within the GetAsync method seems broken when configured to use a single container with different types differentiated by the "Type" field.

This is obviously a critical issue because if someone saves a "Person", then attempts to load and save a "Car", the bug causes this package to deserializes a Person into the Car object, and once saved back into Cosmos will delete all the Person fields.  This is critical as it will lead to corruption and loss of data if this package is used in production.

Taking a quick look, I can see that part of the code handling this inside GetAsync has changed a lot over the last 6-months.  As a temporary work around you can include the filtering inside your own predicate, such as i => i.Type == nameof(MyType) && ....

But obviously the whole point of this package is to do that for you and guarantee it (which appears dangerously broken).  If I get a chance I will look at a fix.  We probably need a test case to make sure this does not regress again given how critical it is.  

Also note that people will not notice this if:
a) They are using separate containers.
or
b) They are only using this package to store a single type in their project.

**Comment by IEvangelist** [comment] 2021-06-15 12:19
Duplicate of #52 - closing this one.

**Closed by IEvangelist** 2021-06-15 12:19 UTC
